[package]
name = "matrix-rs"
version = "1.0.0"
authors = ["deotime"]
description = "Library for using matrices in rust."
keywords = ["matrix", "matrices"]
repository = "https://github.com/DeoTimeTheGithubUser/matrix-rs"
edition = "2021"